// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface_Macro.proto

#ifndef PROTOBUF_Interface_5fMacro_2eproto__INCLUDED
#define PROTOBUF_Interface_5fMacro_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

namespace protobuf_Interface_5fMacro_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_Interface_5fMacro_2eproto

enum Pb_Error {
  Pb_ERROR_MEET_INTERFACE_NULL = 0,
  Pb_ERROR_MEET_INTERFACE_NOTINIT = -1,
  Pb_ERROR_MEET_INTERFACE_MEMORY = -2,
  Pb_ERROR_MEET_INTERFACE_NOSPPORTTYPE = -3,
  Pb_ERROR_MEET_INTERFACE_NOSPPORTMETHOD = -4,
  Pb_ERROR_MEET_INTERFACE_DOWNLOAD = -5,
  Pb_ERROR_MEET_INTERFACE_NETSEND = -6,
  Pb_ERROR_MEET_INTERFACE_NOREADY = -7,
  Pb_ERROR_MEET_INTERFACE_NOFIND = -8,
  Pb_ERROR_MEET_INTERFACE_NOSPPORTPROPERTY = -9,
  Pb_ERROR_MEET_INTERFACE_UPPONMAXVALUE = -10,
  Pb_ERROR_MEET_INTERFACE_ZERO = -11,
  Pb_ERROR_MEET_INTERFACE_PARAMETER = -12,
  Pb_ERROR_MEET_INTERFACE_DATA = -13,
  Pb_Error_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_Error_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_Error_IsValid(int value);
const Pb_Error Pb_Error_MIN = Pb_ERROR_MEET_INTERFACE_DATA;
const Pb_Error Pb_Error_MAX = Pb_ERROR_MEET_INTERFACE_NULL;
const int Pb_Error_ARRAYSIZE = Pb_Error_MAX + 1;

enum Pb_DB_StatusCode {
  Pb_STATUS_MULTIRECORD = 0,
  Pb_STATUS_SINGLERECORDD = 1,
  Pb_STATUS_NORECORED = 2,
  Pb_STATUS_DONE = 3,
  Pb_STATUS_FAIL = 4,
  Pb_STATUS_EXCPT_DB = 5,
  Pb_STATUS_EXCPT_SV = 6,
  Pb_STATUS_ACCESSDENIED = 7,
  Pb_STATUS_PSWFAILED = 8,
  Pb_STATUS_COLL_MEETING = 9,
  Pb_DB_StatusCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_DB_StatusCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_DB_StatusCode_IsValid(int value);
const Pb_DB_StatusCode Pb_DB_StatusCode_MIN = Pb_STATUS_MULTIRECORD;
const Pb_DB_StatusCode Pb_DB_StatusCode_MAX = Pb_STATUS_COLL_MEETING;
const int Pb_DB_StatusCode_ARRAYSIZE = Pb_DB_StatusCode_MAX + 1;

enum Pb_Type {
  Pb_TYPE_MEET_INTERFACE_INITENV = 0,
  Pb_TYPE_MEET_INTERFACE_TIME = 1,
  Pb_TYPE_MEET_INTERFACE_READY = 2,
  Pb_TYPE_MEET_INTERFACE_DOWNLOAD = 3,
  Pb_TYPE_MEET_INTERFACE_UPLOAD = 4,
  Pb_TYPE_MEET_INTERFACE_MEDIAPLAYPOSINFO = 5,
  Pb_TYPE_MEET_INTERFACE_DEVICEINFO = 6,
  Pb_TYPE_MEET_INTERFACE_DEFAULTURL = 7,
  Pb_TYPE_MEET_INTERFACE_ADMIN = 8,
  Pb_TYPE_MEET_INTERFACE_DEVICECONTROL = 9,
  Pb_TYPE_MEET_INTERFACE_PEOPLE = 10,
  Pb_TYPE_MEET_INTERFACE_MEMBER = 11,
  Pb_TYPE_MEET_INTERFACE_MEMBERGROUP = 12,
  Pb_TYPE_MEET_INTERFACE_MEMBERGROUPITEM = 13,
  Pb_TYPE_MEET_INTERFACE_DEVICEFACESHOW = 14,
  Pb_TYPE_MEET_INTERFACE_ROOM = 15,
  Pb_TYPE_MEET_INTERFACE_ROOMDEVICE = 16,
  Pb_TYPE_MEET_INTERFACE_FILEPUSH = 17,
  Pb_TYPE_MEET_INTERFACE_REQUESTSTREAMPUSH = 18,
  Pb_TYPE_MEET_INTERFACE_STREAMPUSH = 19,
  Pb_TYPE_MEET_INTERFACE_MEETINFO = 20,
  Pb_TYPE_MEET_INTERFACE_MEETAGENDA = 21,
  Pb_TYPE_MEET_INTERFACE_MEETBULLET = 22,
  Pb_TYPE_MEET_INTERFACE_MEETDIRECTORY = 23,
  Pb_TYPE_MEET_INTERFACE_MEETDIRECTORYFILE = 24,
  Pb_TYPE_MEET_INTERFACE_MEETDIRECTORYRIGHT = 25,
  Pb_TYPE_MEET_INTERFACE_MEETVIDEO = 26,
  Pb_TYPE_MEET_INTERFACE_MEETTABLECARD = 27,
  Pb_TYPE_MEET_INTERFACE_MEETSEAT = 28,
  Pb_TYPE_MEET_INTERFACE_MEETIM = 29,
  Pb_TYPE_MEET_INTERFACE_MEETONVOTING = 30,
  Pb_TYPE_MEET_INTERFACE_MEETVOTEINFO = 31,
  Pb_TYPE_MEET_INTERFACE_MEETVOTESIGNED = 32,
  Pb_TYPE_MEET_INTERFACE_MANAGEROOM = 33,
  Pb_TYPE_MEET_INTERFACE_MEETSIGN = 34,
  Pb_TYPE_MEET_INTERFACE_WHITEBOARD = 35,
  Pb_TYPE_MEET_INTERFACE_FUNCONFIG = 36,
  Pb_TYPE_MEET_INTERFACE_MEMBERPERMISSION = 37,
  Pb_TYPE_MEET_INTERFACE_PEOPLEGROUP = 38,
  Pb_TYPE_MEET_INTERFACE_PEOPLEGROUPITEM = 39,
  Pb_TYPE_MEET_INTERFACE_SCREENMOUSECONTROL = 40,
  Pb_TYPE_MEET_INTERFACE_SCREENKEYBOARDCONTROL = 41,
  Pb_TYPE_MEET_INTERFACE_DEVICEMEETSTATUS = 42,
  Pb_TYPE_MEET_INTERFACE_DEVICEOPER = 43,
  Pb_TYPE_MEET_INTERFACE_DBSERVERERROR = 44,
  Pb_TYPE_MEET_INTERFACE_MEDIAPLAY = 45,
  Pb_TYPE_MEET_INTERFACE_STREAMPLAY = 46,
  Pb_TYPE_MEET_INTERFACE_STOPPLAY = 47,
  Pb_TYPE_MEET_INTERFACE_MEMBERCOLOR = 48,
  Pb_TYPE_MEET_INTERFACE_MEETCONTEXT = 49,
  Pb_TYPE_MEET_INTERFACE_MEETCLEAR = 50,
  Pb_TYPE_MEET_INTERFACE_MEETSTATISTIC = 51,
  Pb_TYPE_MEET_INTERFACE_MEETFACECONFIG = 52,
  Pb_TYPE_MEET_INTERFACE_MEETSENDMAIL = 53,
  Pb_TYPE_MEET_INTERFACE_FILESCORE = 54,
  Pb_TYPE_MEET_INTERFACE_FILEEVALUATE = 55,
  Pb_TYPE_MEET_INTERFACE_MEETEVALUATE = 56,
  Pb_TYPE_MEET_INTERFACE_SYSTEMLOG = 57,
  Pb_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_Type_IsValid(int value);
const Pb_Type Pb_Type_MIN = Pb_TYPE_MEET_INTERFACE_INITENV;
const Pb_Type Pb_Type_MAX = Pb_TYPE_MEET_INTERFACE_SYSTEMLOG;
const int Pb_Type_ARRAYSIZE = Pb_Type_MAX + 1;

enum Pb_Method {
  Pb_METHOD_MEET_INTERFACE_ZERO = 0,
  Pb_METHOD_MEET_INTERFACE_QUERY = 1,
  Pb_METHOD_MEET_INTERFACE_ADD = 2,
  Pb_METHOD_MEET_INTERFACE_MODIFY = 3,
  Pb_METHOD_MEET_INTERFACE_DEL = 4,
  Pb_METHOD_MEET_INTERFACE_SET = 6,
  Pb_METHOD_MEET_INTERFACE_GETSIZE = 7,
  Pb_METHOD_MEET_INTERFACE_NOTIFY = 8,
  Pb_METHOD_MEET_INTERFACE_CLEAR = 9,
  Pb_METHOD_MEET_INTERFACE_LOGON = 10,
  Pb_METHOD_MEET_INTERFACE_PUSH = 11,
  Pb_METHOD_MEET_INTERFACE_ASK = 12,
  Pb_METHOD_MEET_INTERFACE_REJECT = 13,
  Pb_METHOD_MEET_INTERFACE_EXIT = 14,
  Pb_METHOD_MEET_INTERFACE_OPEN = 15,
  Pb_METHOD_MEET_INTERFACE_CLOSE = 16,
  Pb_METHOD_MEET_INTERFACE_ENTER = 17,
  Pb_METHOD_MEET_INTERFACE_PAGEQUERY = 18,
  Pb_METHOD_MEET_INTERFACE_MODIFYNAME = 19,
  Pb_METHOD_MEET_INTERFACE_MODIFYINFO = 20,
  Pb_METHOD_MEET_INTERFACE_MODIFYSTATUS = 21,
  Pb_METHOD_MEET_INTERFACE_SINGLEQUERYBYID = 22,
  Pb_METHOD_MEET_INTERFACE_SINGLEQUERYBYNAME = 23,
  Pb_METHOD_MEET_INTERFACE_CONTROL = 24,
  Pb_METHOD_MEET_INTERFACE_SAVE = 25,
  Pb_METHOD_MEET_INTERFACE_REFRESH = 26,
  Pb_METHOD_MEET_INTERFACE_COMPLEXQUERY = 27,
  Pb_METHOD_MEET_INTERFACE_COMPLEXPAGEQUERY = 28,
  Pb_METHOD_MEET_INTERFACE_START = 29,
  Pb_METHOD_MEET_INTERFACE_STOP = 30,
  Pb_METHOD_MEET_INTERFACE_PLAY = 31,
  Pb_METHOD_MEET_INTERFACE_PAUSE = 32,
  Pb_METHOD_MEET_INTERFACE_MOVE = 33,
  Pb_METHOD_MEET_INTERFACE_ZOOM = 34,
  Pb_METHOD_MEET_INTERFACE_BACK = 35,
  Pb_METHOD_MEET_INTERFACE_REQUEST = 36,
  Pb_METHOD_MEET_INTERFACE_BROADCAST = 37,
  Pb_METHOD_MEET_INTERFACE_QUERYPROPERTY = 38,
  Pb_METHOD_MEET_INTERFACE_SETPROPERTY = 39,
  Pb_METHOD_MEET_INTERFACE_DUMP = 40,
  Pb_METHOD_MEET_INTERFACE_REQUESTPUSH = 41,
  Pb_METHOD_MEET_INTERFACE_DELALL = 42,
  Pb_METHOD_MEET_INTERFACE_SEND = 43,
  Pb_METHOD_MEET_INTERFACE_DETAILINFO = 44,
  Pb_METHOD_MEET_INTERFACE_INIT = 45,
  Pb_METHOD_MEET_INTERFACE_DESTORY = 46,
  Pb_METHOD_MEET_INTERFACE_MAKEVIDEO = 47,
  Pb_METHOD_MEET_INTERFACE_SUBMIT = 48,
  Pb_METHOD_MEET_INTERFACE_PUBLIST = 49,
  Pb_METHOD_MEET_INTERFACE_CACHE = 50,
  Pb_METHOD_MEET_INTERFACE_CHILDRED = 51,
  Pb_METHOD_MEET_INTERFACE_ALLCHILDRED = 52,
  Pb_METHOD_MEET_INTERFACE_RESPONSE = 53,
  Pb_METHOD_MEET_INTERFACE_REQUESTTOMANAGE = 54,
  Pb_METHOD_MEET_INTERFACE_RESPONSETOMANAGE = 55,
  Pb_METHOD_MEET_INTERFACE_REQUESTPRIVELIGE = 56,
  Pb_METHOD_MEET_INTERFACE_RESPONSEPRIVELIGE = 57,
  Pb_METHOD_MEET_INTERFACE_UPDATE = 58,
  Pb_METHOD_MEET_INTERFACE_TEXTMSG = 59,
  Pb_METHOD_MEET_INTERFACE_REBOOT = 60,
  Pb_METHOD_MEET_INTERFACE_RESINFO = 61,
  Pb_METHOD_MEET_INTERFACE_ADDINK = 1001,
  Pb_METHOD_MEET_INTERFACE_ADDRECT = 1002,
  Pb_METHOD_MEET_INTERFACE_ADDTEXT = 1003,
  Pb_METHOD_MEET_INTERFACE_ADDPICTURE = 1004,
  Pb_Method_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_Method_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_Method_IsValid(int value);
const Pb_Method Pb_Method_MIN = Pb_METHOD_MEET_INTERFACE_ZERO;
const Pb_Method Pb_Method_MAX = Pb_METHOD_MEET_INTERFACE_ADDPICTURE;
const int Pb_Method_ARRAYSIZE = Pb_Method_MAX + 1;

enum Pb_String_LenLimit {
  Pb_STRING_LIMIT_ZERO = 0,
  Pb_MAX_DEVICEIPADDR_NUM = 2,
  Pb_MAX_RES_NUM = 6,
  Pb_MEET_MAX_VOTENUM = 6,
  Pb_SIGNIN_PSW_LEN = 16,
  Pb_MEET_MD5_ASCILL_MAXLEN = 32,
  Pb_FONTNAME_LENG = 48,
  Pb_DEFAULT_NAME_MAXLEN = 48,
  Pb_MEET_NAME_MAXLE = 100,
  Pb_DEFAULT_DESCRIBE_LENG = 100,
  Pb_DEFAULT_SHORT_DESCRIBE_LENG = 40,
  Pb_DEFAULT_PASSWORD_LENG = 40,
  Pb_DEVICE_NAME_MAXLEN = 128,
  Pb_DEVICE_IPADDR_MAXLEN = 64,
  Pb_DEFAULT_FILENAME_LENG = 150,
  Pb_MEET_PATH_MAXLEN = 260,
  Pb_MEET_PATHNAME_MAXLEN = 260,
  Pb_MEET_MEMBERSTRING_MAXLEN = 260,
  Pb_MEET_DEVICESTRING_MAXLEN = 260,
  Pb_MAX_SYSTEMLOG_TEXTLEN = 260,
  Pb_MAX_EVALUATETEXTLEN = 260,
  Pb_MEETIM_CHAR_MSG_MAXLEN = 300,
  Pb_MEETAGENDA_DESCTEXT_LENG = 320,
  Pb_DEFAULT_BULLETCONTENT_LENG = 320,
  Pb_MEET_URL_MAXLEN = 1024,
  Pb_String_LenLimit_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_String_LenLimit_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_String_LenLimit_IsValid(int value);
const Pb_String_LenLimit Pb_String_LenLimit_MIN = Pb_STRING_LIMIT_ZERO;
const Pb_String_LenLimit Pb_String_LenLimit_MAX = Pb_MEET_URL_MAXLEN;
const int Pb_String_LenLimit_ARRAYSIZE = Pb_String_LenLimit_MAX + 1;

enum Pb_ProgramType {
  Pb_MEET_PROGRAM_TYPE_ZERO = 0,
  Pb_MEET_PROGRAM_TYPE_MEETCLIENT = 1,
  Pb_MEET_PROGRAM_TYPE_PROJECTIVE = 2,
  Pb_MEET_PROGRAM_TYPE_STREAMCAPTURE = 3,
  Pb_MEET_PROGRAM_TYPE_SERVICE = 4,
  Pb_MEET_PROGRAM_TYPE_ANDROIDAPP = 5,
  Pb_ProgramType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_ProgramType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_ProgramType_IsValid(int value);
const Pb_ProgramType Pb_ProgramType_MIN = Pb_MEET_PROGRAM_TYPE_ZERO;
const Pb_ProgramType Pb_ProgramType_MAX = Pb_MEET_PROGRAM_TYPE_ANDROIDAPP;
const int Pb_ProgramType_ARRAYSIZE = Pb_ProgramType_MAX + 1;

enum Pb_CacheFlag {
  Pb_MEET_CACEH_FLAG_ZERO = 0,
  Pb_MEET_CACEH_FLAG_FORCE = 1,
  Pb_CacheFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_CacheFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_CacheFlag_IsValid(int value);
const Pb_CacheFlag Pb_CacheFlag_MIN = Pb_MEET_CACEH_FLAG_ZERO;
const Pb_CacheFlag Pb_CacheFlag_MAX = Pb_MEET_CACEH_FLAG_FORCE;
const int Pb_CacheFlag_ARRAYSIZE = Pb_CacheFlag_MAX + 1;

enum Pb_FontAlignFlag {
  Pb_MEET_FONTALIGNFLAG_ZERO = 0,
  Pb_MEET_FONTALIGNFLAG_LEFT = 1,
  Pb_MEET_FONTALIGNFLAG_RIGHT = 2,
  Pb_MEET_FONTALIGNFLAG_HCENTER = 4,
  Pb_MEET_FONTALIGNFLAG_TOP = 8,
  Pb_MEET_FONTALIGNFLAG_BOTTOM = 16,
  Pb_MEET_FONTALIGNFLAG_VCENTER = 32,
  Pb_FontAlignFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_FontAlignFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_FontAlignFlag_IsValid(int value);
const Pb_FontAlignFlag Pb_FontAlignFlag_MIN = Pb_MEET_FONTALIGNFLAG_ZERO;
const Pb_FontAlignFlag Pb_FontAlignFlag_MAX = Pb_MEET_FONTALIGNFLAG_VCENTER;
const int Pb_FontAlignFlag_ARRAYSIZE = Pb_FontAlignFlag_MAX + 1;

enum Pb_DevicePlayStatus {
  Pb_DEVICE_PLAYSTATUS_IDLE = 0,
  Pb_DEVICE_PLAYSTATUS_MEDIA = 1,
  Pb_DEVICE_PLAYSTATUS_STREAM = 2,
  Pb_DEVICE_PLAYSTATUS_TALK = 3,
  Pb_DevicePlayStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_DevicePlayStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_DevicePlayStatus_IsValid(int value);
const Pb_DevicePlayStatus Pb_DevicePlayStatus_MIN = Pb_DEVICE_PLAYSTATUS_IDLE;
const Pb_DevicePlayStatus Pb_DevicePlayStatus_MAX = Pb_DEVICE_PLAYSTATUS_TALK;
const int Pb_DevicePlayStatus_ARRAYSIZE = Pb_DevicePlayStatus_MAX + 1;

enum Pb_MeetFaceStatus {
  Pb_MemState_MainFace = 0,
  Pb_MemState_MemFace = 1,
  Pb_MemState_AdminFace = 2,
  Pb_MeetFaceStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFaceStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFaceStatus_IsValid(int value);
const Pb_MeetFaceStatus Pb_MeetFaceStatus_MIN = Pb_MemState_MainFace;
const Pb_MeetFaceStatus Pb_MeetFaceStatus_MAX = Pb_MemState_AdminFace;
const int Pb_MeetFaceStatus_ARRAYSIZE = Pb_MeetFaceStatus_MAX + 1;

enum Pb_MeetDevicePropertyID {
  Pb_MEETDEVICE_PROPERTY_ZERO = 0,
  Pb_MEETDEVICE_PROPERTY_NAME = 1,
  Pb_MEETDEVICE_PROPERTY_IPADDR = 2,
  Pb_MEETDEVICE_PROPERTY_PORT = 3,
  Pb_MEETDEVICE_PROPERTY_NETSTATUS = 4,
  Pb_MEETDEVICE_PROPERTY_PLAYSTATUS = 5,
  Pb_MEETDEVICE_PROPERTY_FACESTATUS = 6,
  Pb_MEETDEVICE_PROPERTY_MEMBERID = 7,
  Pb_MEETDEVICE_PROPERTY_MEETINGID = 8,
  Pb_MEETDEVICE_PROPERTY_TRIGGERID = 9,
  Pb_MEETDEVICE_PROPERTY_STREAMNAME = 10,
  Pb_MeetDevicePropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetDevicePropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetDevicePropertyID_IsValid(int value);
const Pb_MeetDevicePropertyID Pb_MeetDevicePropertyID_MIN = Pb_MEETDEVICE_PROPERTY_ZERO;
const Pb_MeetDevicePropertyID Pb_MeetDevicePropertyID_MAX = Pb_MEETDEVICE_PROPERTY_STREAMNAME;
const int Pb_MeetDevicePropertyID_ARRAYSIZE = Pb_MeetDevicePropertyID_MAX + 1;

enum Pb_DeviceModifyFlag {
  Pb_DEVICE_MODIFYFLAG_ZERO = 0,
  Pb_DEVICE_MODIFYFLAG_NAME = 1,
  Pb_DEVICE_MODIFYFLAG_IPADDR = 2,
  Pb_DEVICE_MODIFYFLAG_PORT = 4,
  Pb_DEVICE_MODIFYFLAG_LIFTRES = 8,
  Pb_DeviceModifyFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_DeviceModifyFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_DeviceModifyFlag_IsValid(int value);
const Pb_DeviceModifyFlag Pb_DeviceModifyFlag_MIN = Pb_DEVICE_MODIFYFLAG_ZERO;
const Pb_DeviceModifyFlag Pb_DeviceModifyFlag_MAX = Pb_DEVICE_MODIFYFLAG_LIFTRES;
const int Pb_DeviceModifyFlag_ARRAYSIZE = Pb_DeviceModifyFlag_MAX + 1;

enum Pb_ContextPropertyID {
  Pb_MEETCONTEXT_PROPERTY_ZERO = 0,
  Pb_MEETCONTEXT_PROPERTY_ROLE = 1,
  Pb_MEETCONTEXT_PROPERTY_CURADMINID = 2,
  Pb_MEETCONTEXT_PROPERTY_CURADMINNAME = 3,
  Pb_MEETCONTEXT_PROPERTY_CURADMINPASSWORD = 4,
  Pb_MEETCONTEXT_PROPERTY_HASTABLECARD = 5,
  Pb_MEETCONTEXT_PROPERTY_CURMEETINGID = 6,
  Pb_MEETCONTEXT_PROPERTY_SELFID = 7,
  Pb_MEETCONTEXT_PROPERTY_CURROOMID = 8,
  Pb_MEETCONTEXT_PROPERTY_SELFMEMBERID = 9,
  Pb_MEETCONTEXT_PROPERTY_MEETDBDEVICEID = 10,
  Pb_MEETCONTEXT_PROPERTY_SCREENSTREAMINDEX = 11,
  Pb_ContextPropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_ContextPropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_ContextPropertyID_IsValid(int value);
const Pb_ContextPropertyID Pb_ContextPropertyID_MIN = Pb_MEETCONTEXT_PROPERTY_ZERO;
const Pb_ContextPropertyID Pb_ContextPropertyID_MAX = Pb_MEETCONTEXT_PROPERTY_SCREENSTREAMINDEX;
const int Pb_ContextPropertyID_ARRAYSIZE = Pb_ContextPropertyID_MAX + 1;

enum Pb_AgendaType {
  Pb_MEET_AGENDA_TYPE_TEXT = 0,
  Pb_MEET_AGENDA_TYPE_FILE = 1,
  Pb_MEET_AGENDA_TYPE_TIME = 2,
  Pb_AgendaType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_AgendaType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_AgendaType_IsValid(int value);
const Pb_AgendaType Pb_AgendaType_MIN = Pb_MEET_AGENDA_TYPE_TEXT;
const Pb_AgendaType Pb_AgendaType_MAX = Pb_MEET_AGENDA_TYPE_TIME;
const int Pb_AgendaType_ARRAYSIZE = Pb_AgendaType_MAX + 1;

enum Pb_AgendaStatus {
  Pb_MEETAGENDA_STATUS_IDLE = 0,
  Pb_MEETAGENDA_STATUS_RUNNING = 1,
  Pb_MEETAGENDA_STATUS_END = 2,
  Pb_AgendaStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_AgendaStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_AgendaStatus_IsValid(int value);
const Pb_AgendaStatus Pb_AgendaStatus_MIN = Pb_MEETAGENDA_STATUS_IDLE;
const Pb_AgendaStatus Pb_AgendaStatus_MAX = Pb_MEETAGENDA_STATUS_END;
const int Pb_AgendaStatus_ARRAYSIZE = Pb_AgendaStatus_MAX + 1;

enum Pb_AdminLogonStatus {
  Pb_ADMINLOGON_ERR_NONE = 0,
  Pb_ADMINLOGON_ERR_PSW = 1,
  Pb_ADMINLOGON_ERR_EXCPT_SV = 2,
  Pb_ADMINLOGON_ERR_EXCPT_DB = 3,
  Pb_AdminLogonStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_AdminLogonStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_AdminLogonStatus_IsValid(int value);
const Pb_AdminLogonStatus Pb_AdminLogonStatus_MIN = Pb_ADMINLOGON_ERR_NONE;
const Pb_AdminLogonStatus Pb_AdminLogonStatus_MAX = Pb_ADMINLOGON_ERR_EXCPT_DB;
const int Pb_AdminLogonStatus_ARRAYSIZE = Pb_AdminLogonStatus_MAX + 1;

enum Pb_DeviceControlFlag {
  Pb_DEVICECONTORL_ZERO = 0,
  Pb_DEVICECONTORL_SHUTDOWN = 1,
  Pb_DEVICECONTORL_REBOOT = 2,
  Pb_DEVICECONTORL_PROGRAMRESTART = 3,
  Pb_DEVICECONTORL_LIFTUP = 4,
  Pb_DEVICECONTORL_LIFTDOWN = 5,
  Pb_DEVICECONTORL_LIFTSTOP = 6,
  Pb_DEVICECONTORL_MODIFYLOGO = 7,
  Pb_DEVICECONTORL_MODIFYMAINBG = 8,
  Pb_DEVICECONTORL_MODIFYPROJECTBG = 9,
  Pb_DEVICECONTORL_MODIFYSUBBG = 10,
  Pb_DEVICECONTORL_MODIFYFONTCOLOR = 11,
  Pb_DeviceControlFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_DeviceControlFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_DeviceControlFlag_IsValid(int value);
const Pb_DeviceControlFlag Pb_DeviceControlFlag_MIN = Pb_DEVICECONTORL_ZERO;
const Pb_DeviceControlFlag Pb_DeviceControlFlag_MAX = Pb_DEVICECONTORL_MODIFYFONTCOLOR;
const int Pb_DeviceControlFlag_ARRAYSIZE = Pb_DeviceControlFlag_MAX + 1;

enum Pb_LiftFlag {
  Pb_LIFT_FLAG_ZERO = 0,
  Pb_LIFT_FLAG_MACHICE = 1,
  Pb_LIFT_FLAG_MIC = 2,
  Pb_LiftFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_LiftFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_LiftFlag_IsValid(int value);
const Pb_LiftFlag Pb_LiftFlag_MIN = Pb_LIFT_FLAG_ZERO;
const Pb_LiftFlag Pb_LiftFlag_MAX = Pb_LIFT_FLAG_MIC;
const int Pb_LiftFlag_ARRAYSIZE = Pb_LiftFlag_MAX + 1;

enum Pb_Download_State {
  Pb_STATE_MEDIA_DOWNLOAD_IDLE = 0,
  Pb_STATE_MEDIA_DOWNLOAD_WORKING = 1,
  Pb_STATE_MEDIA_DOWNLOAD_FINISH = 2,
  Pb_STATE_MEDIA_DOWNLOAD_ERROR = 3,
  Pb_STATE_MEDIA_DOWNLOAD_EXIT = 4,
  Pb_STATE_MEDIA_DOWNLOAD_DESTROY = 5,
  Pb_Download_State_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_Download_State_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_Download_State_IsValid(int value);
const Pb_Download_State Pb_Download_State_MIN = Pb_STATE_MEDIA_DOWNLOAD_IDLE;
const Pb_Download_State Pb_Download_State_MAX = Pb_STATE_MEDIA_DOWNLOAD_DESTROY;
const int Pb_Download_State_ARRAYSIZE = Pb_Download_State_MAX + 1;

enum Pb_Download_Erro {
  Pb_ERROR_MEDIA_DOWNLOAD_OK = 0,
  Pb_ERROR_MEDIA_DOWNLOAD_PARAMETER = 1,
  Pb_ERROR_MEDIA_DOWNLOAD_INITTHREAD = 2,
  Pb_ERROR_MEDIA_DOWNLOAD_USERSTOP = 3,
  Pb_ERROR_MEDIA_DOWNLOAD_NOMEDIA = 4,
  Pb_ERROR_MEDIA_DOWNLOAD_OPEN = 5,
  Pb_ERROR_MEDIA_DOWNLOAD_FILEOK = 6,
  Pb_ERROR_MEDIA_DOWNLOAD_CREATE = 7,
  Pb_ERROR_MEDIA_DOWNLOAD_MEMORY = 8,
  Pb_ERROR_MEDIA_DOWNLOAD_EXECINIT = 9,
  Pb_ERROR_MEDIA_DOWNLOAD_SETPOS = 10,
  Pb_Download_Erro_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_Download_Erro_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_Download_Erro_IsValid(int value);
const Pb_Download_Erro Pb_Download_Erro_MIN = Pb_ERROR_MEDIA_DOWNLOAD_OK;
const Pb_Download_Erro Pb_Download_Erro_MAX = Pb_ERROR_MEDIA_DOWNLOAD_SETPOS;
const int Pb_Download_Erro_ARRAYSIZE = Pb_Download_Erro_MAX + 1;

enum Pb_Upload_State {
  Pb_UPLOADMEDIA_FLAG_IDLE = 0,
  Pb_UPLOADMEDIA_FLAG_UPLOADING = 1,
  Pb_UPLOADMEDIA_FLAG_STOP = 2,
  Pb_UPLOADMEDIA_FLAG_HADEND = 3,
  Pb_UPLOADMEDIA_FLAG_NOSERVER = 4,
  Pb_UPLOADMEDIA_FLAG_ISBEING = 5,
  Pb_Upload_State_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_Upload_State_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_Upload_State_IsValid(int value);
const Pb_Upload_State Pb_Upload_State_MIN = Pb_UPLOADMEDIA_FLAG_IDLE;
const Pb_Upload_State Pb_Upload_State_MAX = Pb_UPLOADMEDIA_FLAG_ISBEING;
const int Pb_Upload_State_ARRAYSIZE = Pb_Upload_State_MAX + 1;

enum Pb_Upload_Flag {
  Pb_MEET_UPLOADFLAG_ZERO = 0,
  Pb_MEET_UPLOADFLAG_ONLYENDCALLBACK = 1,
  Pb_Upload_Flag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_Upload_Flag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_Upload_Flag_IsValid(int value);
const Pb_Upload_Flag Pb_Upload_Flag_MIN = Pb_MEET_UPLOADFLAG_ZERO;
const Pb_Upload_Flag Pb_Upload_Flag_MAX = Pb_MEET_UPLOADFLAG_ONLYENDCALLBACK;
const int Pb_Upload_Flag_ARRAYSIZE = Pb_Upload_Flag_MAX + 1;

enum Pb_MemberPropertyID {
  Pb_MEETMEMBER_PROPERTY_ZERO = 0,
  Pb_MEETMEMBER_PROPERTY_NAME = 1,
  Pb_MEETMEMBER_PROPERTY_COMPANY = 2,
  Pb_MEETMEMBER_PROPERTY_JOB = 3,
  Pb_MEETMEMBER_PROPERTY_COMMENT = 4,
  Pb_MEETMEMBER_PROPERTY_PHONE = 5,
  Pb_MEETMEMBER_PROPERTY_EMAIL = 6,
  Pb_MEETMEMBER_PROPERTY_PASSWORD = 7,
  Pb_MemberPropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MemberPropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MemberPropertyID_IsValid(int value);
const Pb_MemberPropertyID Pb_MemberPropertyID_MIN = Pb_MEETMEMBER_PROPERTY_ZERO;
const Pb_MemberPropertyID Pb_MemberPropertyID_MAX = Pb_MEETMEMBER_PROPERTY_PASSWORD;
const int Pb_MemberPropertyID_ARRAYSIZE = Pb_MemberPropertyID_MAX + 1;

enum Pb_MemberPermissionPropertyID {
  Pb_memperm_zero = 0,
  Pb_memperm_sscreen = 1,
  Pb_memperm_projective = 2,
  Pb_memperm_upload = 4,
  Pb_memperm_download = 8,
  Pb_memperm_vote = 16,
  Pb_MemberPermissionPropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MemberPermissionPropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MemberPermissionPropertyID_IsValid(int value);
const Pb_MemberPermissionPropertyID Pb_MemberPermissionPropertyID_MIN = Pb_memperm_zero;
const Pb_MemberPermissionPropertyID Pb_MemberPermissionPropertyID_MAX = Pb_memperm_vote;
const int Pb_MemberPermissionPropertyID_ARRAYSIZE = Pb_MemberPermissionPropertyID_MAX + 1;

enum Pb_MeetSignType {
  Pb_signin_direct = 0,
  Pb_signin_psw = 1,
  Pb_signin_photo = 2,
  Pb_signin_onepsw = 3,
  Pb_signin_onepsw_photo = 4,
  Pb_signin_psw_photo = 5,
  Pb_MeetSignType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetSignType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetSignType_IsValid(int value);
const Pb_MeetSignType Pb_MeetSignType_MIN = Pb_signin_direct;
const Pb_MeetSignType Pb_MeetSignType_MAX = Pb_signin_psw_photo;
const int Pb_MeetSignType_ARRAYSIZE = Pb_MeetSignType_MAX + 1;

enum Pb_MeetRoomPropertyID {
  Pb_MEETROOM_PROPERTY_ZERO = 0,
  Pb_MEETROOM_PROPERTY_BGPHOTOID = 1,
  Pb_MEETSEAT_PROPERTY_MANAGERID = 2,
  Pb_MeetRoomPropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetRoomPropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetRoomPropertyID_IsValid(int value);
const Pb_MeetRoomPropertyID Pb_MeetRoomPropertyID_MIN = Pb_MEETROOM_PROPERTY_ZERO;
const Pb_MeetRoomPropertyID Pb_MeetRoomPropertyID_MAX = Pb_MEETSEAT_PROPERTY_MANAGERID;
const int Pb_MeetRoomPropertyID_ARRAYSIZE = Pb_MeetRoomPropertyID_MAX + 1;

enum Pb_DeviceDirection {
  Pb_SEATDIRECTION_UP = 0,
  Pb_SEATDIRECTION_DOWN = 1,
  Pb_SEATDIRECTION_LEFT = 2,
  Pb_SEATDIRECTION_RIGHT = 3,
  Pb_DeviceDirection_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_DeviceDirection_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_DeviceDirection_IsValid(int value);
const Pb_DeviceDirection Pb_DeviceDirection_MIN = Pb_SEATDIRECTION_UP;
const Pb_DeviceDirection Pb_DeviceDirection_MAX = Pb_SEATDIRECTION_RIGHT;
const int Pb_DeviceDirection_ARRAYSIZE = Pb_DeviceDirection_MAX + 1;

enum Pb_RoomDeviceFilterFlag {
  Pb_MEET_ROOMDEVICE_FLAG_ZERO = 0,
  Pb_MEET_ROOMDEVICE_FLAG_ONLINE = 1,
  Pb_MEET_ROOMDEVICE_FLAG_FACESTATUS = 2,
  Pb_MEET_ROOMDEVICE_FLAG_BINDMEMBER = 4,
  Pb_MEET_ROOMDEVICE_FLAG_PROJECTIVE = 8,
  Pb_MEET_ROOMDEVICE_FLAG_HADSIGNIN = 16,
  Pb_MEET_ROOMDEVICE_FLAG_NOSELFID = 32,
  Pb_MEET_ROOMDEVICE_FLAG_NODEVID = 64,
  Pb_RoomDeviceFilterFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_RoomDeviceFilterFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_RoomDeviceFilterFlag_IsValid(int value);
const Pb_RoomDeviceFilterFlag Pb_RoomDeviceFilterFlag_MIN = Pb_MEET_ROOMDEVICE_FLAG_ZERO;
const Pb_RoomDeviceFilterFlag Pb_RoomDeviceFilterFlag_MAX = Pb_MEET_ROOMDEVICE_FLAG_NODEVID;
const int Pb_RoomDeviceFilterFlag_ARRAYSIZE = Pb_RoomDeviceFilterFlag_MAX + 1;

enum Pb_MeetStatus {
  Pb_MEETING_STATUS_Ready = 0,
  Pb_MEETING_STATUS_Start = 1,
  Pb_MEETING_STATUS_End = 2,
  Pb_MEETING_STATUS_PAUSE = 3,
  Pb_MeetStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetStatus_IsValid(int value);
const Pb_MeetStatus Pb_MeetStatus_MIN = Pb_MEETING_STATUS_Ready;
const Pb_MeetStatus Pb_MeetStatus_MAX = Pb_MEETING_STATUS_PAUSE;
const int Pb_MeetStatus_ARRAYSIZE = Pb_MeetStatus_MAX + 1;

enum Pb_MeetPropertyID {
  Pb_MEET_PROPERTY_ZERO = 0,
  Pb_MEET_PROPERTY_SECRECY = 1,
  Pb_MEET_PROPERTY_ROOMID = 2,
  Pb_MEET_PROPERTY_SIGNINTYPE = 3,
  Pb_MEET_PROPERTY_MANAGERID = 4,
  Pb_MEET_PROPERTY_STATUS = 5,
  Pb_MEET_PROPERTY_STARTTIME = 6,
  Pb_MEET_PROPERTY_ENDTIME = 7,
  Pb_MeetPropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetPropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetPropertyID_IsValid(int value);
const Pb_MeetPropertyID Pb_MeetPropertyID_MIN = Pb_MEET_PROPERTY_ZERO;
const Pb_MeetPropertyID Pb_MeetPropertyID_MAX = Pb_MEET_PROPERTY_ENDTIME;
const int Pb_MeetPropertyID_ARRAYSIZE = Pb_MeetPropertyID_MAX + 1;

enum Pb_MeetMemberRole {
  Pb_role_member_nouser = 0,
  Pb_role_member_normal = 1,
  Pb_role_member_compere = 3,
  Pb_role_member_secretary = 4,
  Pb_role_device_projector = 8,
  Pb_role_admin = 9,
  Pb_MeetMemberRole_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetMemberRole_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetMemberRole_IsValid(int value);
const Pb_MeetMemberRole Pb_MeetMemberRole_MIN = Pb_role_member_nouser;
const Pb_MeetMemberRole Pb_MeetMemberRole_MAX = Pb_role_admin;
const int Pb_MeetMemberRole_ARRAYSIZE = Pb_MeetMemberRole_MAX + 1;

enum Pb_MeetFileAttrib {
  Pb_MEETFILE_ATTRIB_ZERO = 0,
  Pb_MEETFILE_ATTRIB_IMPORTANTFILE = 1,
  Pb_MeetFileAttrib_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFileAttrib_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFileAttrib_IsValid(int value);
const Pb_MeetFileAttrib Pb_MeetFileAttrib_MIN = Pb_MEETFILE_ATTRIB_ZERO;
const Pb_MeetFileAttrib Pb_MeetFileAttrib_MAX = Pb_MEETFILE_ATTRIB_IMPORTANTFILE;
const int Pb_MeetFileAttrib_ARRAYSIZE = Pb_MeetFileAttrib_MAX + 1;

enum Pb_MeetFilePropertyID {
  Pb_MEETFILE_PROPERTY_ZERO = 0,
  Pb_MEETFILE_PROPERTY_NAME = 1,
  Pb_MEETFILE_PROPERTY_SIZE = 2,
  Pb_MEETFILE_PROPERTY_TIME = 3,
  Pb_MEETFILE_PROPERTY_ATTRIB = 4,
  Pb_MeetFilePropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFilePropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFilePropertyID_IsValid(int value);
const Pb_MeetFilePropertyID Pb_MeetFilePropertyID_MIN = Pb_MEETFILE_PROPERTY_ZERO;
const Pb_MeetFilePropertyID Pb_MeetFilePropertyID_MAX = Pb_MEETFILE_PROPERTY_ATTRIB;
const int Pb_MeetFilePropertyID_ARRAYSIZE = Pb_MeetFilePropertyID_MAX + 1;

enum Pb_MeetFileQueryFlag {
  Pb_MEET_FILETYPE_QUERYFLAG_ZERO = 0,
  Pb_MEET_FILETYPE_QUERYFLAG_UPLOADID = 1,
  Pb_MEET_FILETYPE_QUERYFLAG_FILETYPE = 2,
  Pb_MEET_FILETYPE_QUERYFLAG_ATTRIB = 4,
  Pb_MEET_FILETYPE_QUERYFLAG_IMPORTANTFRONT = 8,
  Pb_MeetFileQueryFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFileQueryFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFileQueryFlag_IsValid(int value);
const Pb_MeetFileQueryFlag Pb_MeetFileQueryFlag_MIN = Pb_MEET_FILETYPE_QUERYFLAG_ZERO;
const Pb_MeetFileQueryFlag Pb_MeetFileQueryFlag_MAX = Pb_MEET_FILETYPE_QUERYFLAG_IMPORTANTFRONT;
const int Pb_MeetFileQueryFlag_ARRAYSIZE = Pb_MeetFileQueryFlag_MAX + 1;

enum Pb_MeetFileType {
  Pb_MEET_FILETYPE_ZERO = 0,
  Pb_MEET_FILETYPE_AUDIO = 1,
  Pb_MEET_FILETYPE_VIDEO = 2,
  Pb_MEET_FILETYPE_PICTURE = 4,
  Pb_MEET_FILETYPE_DOCUMENT = 8,
  Pb_MEET_FILETYPE_OTHER = 16,
  Pb_MeetFileType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFileType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFileType_IsValid(int value);
const Pb_MeetFileType Pb_MeetFileType_MIN = Pb_MEET_FILETYPE_ZERO;
const Pb_MeetFileType Pb_MeetFileType_MAX = Pb_MEET_FILETYPE_OTHER;
const int Pb_MeetFileType_ARRAYSIZE = Pb_MeetFileType_MAX + 1;

enum Pb_TableCardType {
  Pb_conf_zero = 0,
  Pb_conf_mtgname = 1,
  Pb_conf_memname = 2,
  Pb_conf_job = 3,
  Pb_conf_company = 4,
  Pb_conf_position = 5,
  Pb_TableCardType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_TableCardType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_TableCardType_IsValid(int value);
const Pb_TableCardType Pb_TableCardType_MIN = Pb_conf_zero;
const Pb_TableCardType Pb_TableCardType_MAX = Pb_conf_position;
const int Pb_TableCardType_ARRAYSIZE = Pb_TableCardType_MAX + 1;

enum Pb_TableCardFlag {
  Pb_MEET_TABLECARDFLAG_ZERO = 0,
  Pb_MEET_TABLECARDFLAG_SHOW = 1,
  Pb_MEET_TABLECARDFLAG_BOLD = 2,
  Pb_MEET_TABLECARDFLAG_LEAN = 4,
  Pb_MEET_TABLECARDFLAG_UNDERLINE = 8,
  Pb_TableCardFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_TableCardFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_TableCardFlag_IsValid(int value);
const Pb_TableCardFlag Pb_TableCardFlag_MIN = Pb_MEET_TABLECARDFLAG_ZERO;
const Pb_TableCardFlag Pb_TableCardFlag_MAX = Pb_MEET_TABLECARDFLAG_UNDERLINE;
const int Pb_TableCardFlag_ARRAYSIZE = Pb_TableCardFlag_MAX + 1;

enum Pb_MeetSeatPropertyID {
  Pb_MEETSEAT_PROPERTY_ZERO = 0,
  Pb_MEETSEAT_PROPERTY_SEATID = 1,
  Pb_MEETSEAT_PROPERTY_MEMBERID = 2,
  Pb_MEETSEAT_PROPERTY_ROLEBYMEMBERID = 3,
  Pb_MEETSEAT_PROPERTY_ROLEBYDEVICEID = 4,
  Pb_MEETSEAT_PROPERTY_ISCOMPEREEBYMEMBERID = 5,
  Pb_MEETSEAT_PROPERTY_ISCOMPEREEBYDEVICEID = 6,
  Pb_MEETSEAT_PROPERTY_MEMBERIDBYROLE = 7,
  Pb_MEETSEAT_PROPERTY_DEVICEIDBYROLE = 8,
  Pb_MeetSeatPropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetSeatPropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetSeatPropertyID_IsValid(int value);
const Pb_MeetSeatPropertyID Pb_MeetSeatPropertyID_MIN = Pb_MEETSEAT_PROPERTY_ZERO;
const Pb_MeetSeatPropertyID Pb_MeetSeatPropertyID_MAX = Pb_MEETSEAT_PROPERTY_DEVICEIDBYROLE;
const int Pb_MeetSeatPropertyID_ARRAYSIZE = Pb_MeetSeatPropertyID_MAX + 1;

enum Pb_MeetIMMSG_TYPE {
  Pb_MEETIM_CHAT_Message = 0,
  Pb_MEETIM_CHAT_Link = 1,
  Pb_MEETIM_CHAT_Water = 2,
  Pb_MEETIM_CHAT_Tea = 3,
  Pb_MEETIM_CHAT_Coffee = 4,
  Pb_MEETIM_CHAT_Pen = 5,
  Pb_MEETIM_CHAT_Paper = 6,
  Pb_MEETIM_CHAT_Technical = 7,
  Pb_MEETIM_CHAT_Waiter = 8,
  Pb_MEETIM_CHAT_Other = 9,
  Pb_MEETIM_CHAT_Emecc = 10,
  Pb_MeetIMMSG_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetIMMSG_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetIMMSG_TYPE_IsValid(int value);
const Pb_MeetIMMSG_TYPE Pb_MeetIMMSG_TYPE_MIN = Pb_MEETIM_CHAT_Message;
const Pb_MeetIMMSG_TYPE Pb_MeetIMMSG_TYPE_MAX = Pb_MEETIM_CHAT_Emecc;
const int Pb_MeetIMMSG_TYPE_ARRAYSIZE = Pb_MeetIMMSG_TYPE_MAX + 1;

enum Pb_MeetIMMSG_QueryFlag {
  Pb_COMPLEXQUERY_ZERO = 0,
  Pb_COMPLEXQUERY_MSGTYPE = 1,
  Pb_COMPLEXQUERY_ROLE = 2,
  Pb_COMPLEXQUERY_MEMBERID = 4,
  Pb_COMPLEXQUERY_UTCTIME = 8,
  Pb_MeetIMMSG_QueryFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetIMMSG_QueryFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetIMMSG_QueryFlag_IsValid(int value);
const Pb_MeetIMMSG_QueryFlag Pb_MeetIMMSG_QueryFlag_MIN = Pb_COMPLEXQUERY_ZERO;
const Pb_MeetIMMSG_QueryFlag Pb_MeetIMMSG_QueryFlag_MAX = Pb_COMPLEXQUERY_UTCTIME;
const int Pb_MeetIMMSG_QueryFlag_ARRAYSIZE = Pb_MeetIMMSG_QueryFlag_MAX + 1;

enum Pb_MeetVoteStatus {
  Pb_vote_notvote = 0,
  Pb_vote_voteing = 1,
  Pb_vote_endvote = 2,
  Pb_MeetVoteStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetVoteStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetVoteStatus_IsValid(int value);
const Pb_MeetVoteStatus Pb_MeetVoteStatus_MIN = Pb_vote_notvote;
const Pb_MeetVoteStatus Pb_MeetVoteStatus_MAX = Pb_vote_endvote;
const int Pb_MeetVoteStatus_ARRAYSIZE = Pb_MeetVoteStatus_MAX + 1;

enum Pb_MeetVoteType {
  Pb_VOTE_MAINTYPE_vote = 0,
  Pb_VOTE_MAINTYPE_election = 1,
  Pb_VOTE_MAINTYPE_questionnaire = 2,
  Pb_MeetVoteType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetVoteType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetVoteType_IsValid(int value);
const Pb_MeetVoteType Pb_MeetVoteType_MIN = Pb_VOTE_MAINTYPE_vote;
const Pb_MeetVoteType Pb_MeetVoteType_MAX = Pb_VOTE_MAINTYPE_questionnaire;
const int Pb_MeetVoteType_ARRAYSIZE = Pb_MeetVoteType_MAX + 1;

enum Pb_MeetVoteMode {
  Pb_VOTEMODE_agonymous = 0,
  Pb_VOTEMODE_signed = 1,
  Pb_MeetVoteMode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetVoteMode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetVoteMode_IsValid(int value);
const Pb_MeetVoteMode Pb_MeetVoteMode_MIN = Pb_VOTEMODE_agonymous;
const Pb_MeetVoteMode Pb_MeetVoteMode_MAX = Pb_VOTEMODE_signed;
const int Pb_MeetVoteMode_ARRAYSIZE = Pb_MeetVoteMode_MAX + 1;

enum Pb_MeetVote_SelType {
  Pb_VOTE_TYPE_MANY = 0,
  Pb_VOTE_TYPE_SINGLE = 1,
  Pb_VOTE_TYPE_4_5 = 2,
  Pb_VOTE_TYPE_3_5 = 3,
  Pb_VOTE_TYPE_2_5 = 4,
  Pb_VOTE_TYPE_2_3 = 5,
  Pb_MeetVote_SelType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetVote_SelType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetVote_SelType_IsValid(int value);
const Pb_MeetVote_SelType Pb_MeetVote_SelType_MIN = Pb_VOTE_TYPE_MANY;
const Pb_MeetVote_SelType Pb_MeetVote_SelType_MAX = Pb_VOTE_TYPE_2_3;
const int Pb_MeetVote_SelType_ARRAYSIZE = Pb_MeetVote_SelType_MAX + 1;

enum Pb_MeetVotePropertyID {
  Pb_MEETVOTE_PROPERTY_ZERO = 0,
  Pb_MEETVOTE_PROPERTY_HADSIGNIN = 1,
  Pb_MEETVOTE_PROPERTY_SIGNINITEM = 2,
  Pb_MeetVotePropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetVotePropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetVotePropertyID_IsValid(int value);
const Pb_MeetVotePropertyID Pb_MeetVotePropertyID_MIN = Pb_MEETVOTE_PROPERTY_ZERO;
const Pb_MeetVotePropertyID Pb_MeetVotePropertyID_MAX = Pb_MEETVOTE_PROPERTY_SIGNINITEM;
const int Pb_MeetVotePropertyID_ARRAYSIZE = Pb_MeetVotePropertyID_MAX + 1;

enum Pb_MeetSignPropertyID {
  Pb_MEETTSIGN_PROPERTY_ZERO = 0,
  Pb_MEETTSIGN_PROPERTY_HADSIGNIN = 1,
  Pb_MEETTSIGN_PROPERTY_SIGNINTYPE = 2,
  Pb_MeetSignPropertyID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetSignPropertyID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetSignPropertyID_IsValid(int value);
const Pb_MeetSignPropertyID Pb_MeetSignPropertyID_MIN = Pb_MEETTSIGN_PROPERTY_ZERO;
const Pb_MeetSignPropertyID Pb_MeetSignPropertyID_MAX = Pb_MEETTSIGN_PROPERTY_SIGNINTYPE;
const int Pb_MeetSignPropertyID_ARRAYSIZE = Pb_MeetSignPropertyID_MAX + 1;

enum Pb_MeetPostilOperType {
  Pb_MEETPOTIL_FLAG_ZERO = 0,
  Pb_MEETPOTIL_FLAG_FORCEOPEN = 1,
  Pb_MEETPOTIL_FLAG_FORCECLOSE = 2,
  Pb_MEETPOTIL_FLAG_REQUESTOPEN = 3,
  Pb_MEETPOTIL_FLAG_REJECTOPEN = 4,
  Pb_MEETPOTIL_FLAG_EXIT = 5,
  Pb_MEETPOTIL_FLAG_ENTER = 6,
  Pb_MeetPostilOperType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetPostilOperType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetPostilOperType_IsValid(int value);
const Pb_MeetPostilOperType Pb_MeetPostilOperType_MIN = Pb_MEETPOTIL_FLAG_ZERO;
const Pb_MeetPostilOperType Pb_MeetPostilOperType_MAX = Pb_MEETPOTIL_FLAG_ENTER;
const int Pb_MeetPostilOperType_ARRAYSIZE = Pb_MeetPostilOperType_MAX + 1;

enum Pb_MeetPostilFigureType {
  Pb_WB_FIGURETYPE_ZERO = 0,
  Pb_WB_FIGURETYPE_INK = 1,
  Pb_WB_FIGURETYPE_LINE = 2,
  Pb_WB_FIGURETYPE_ELLIPSE = 3,
  Pb_WB_FIGURETYPE_RECTANGLE = 4,
  Pb_WB_FIGURETYPE_FREETEXT = 5,
  Pb_WB_FIGURETYPE_PICTURE = 6,
  Pb_WB_FIGURETYPE_ARROW = 7,
  Pb_MeetPostilFigureType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetPostilFigureType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetPostilFigureType_IsValid(int value);
const Pb_MeetPostilFigureType Pb_MeetPostilFigureType_MIN = Pb_WB_FIGURETYPE_ZERO;
const Pb_MeetPostilFigureType Pb_MeetPostilFigureType_MAX = Pb_WB_FIGURETYPE_ARROW;
const int Pb_MeetPostilFigureType_ARRAYSIZE = Pb_MeetPostilFigureType_MAX + 1;

enum Pb_MeetFontFlag {
  Pb_WHITEBOARD_FONT_ZERO = 0,
  Pb_WHITEBOARD_FONT_STRIKEOUT = 1,
  Pb_WHITEBOARD_FONT_BOLD = 2,
  Pb_WHITEBOARD_FONT_ITALIC = 4,
  Pb_WHITEBOARD_FONT_UNDERLINE = 8,
  Pb_MeetFontFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFontFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFontFlag_IsValid(int value);
const Pb_MeetFontFlag Pb_MeetFontFlag_MIN = Pb_WHITEBOARD_FONT_ZERO;
const Pb_MeetFontFlag Pb_MeetFontFlag_MAX = Pb_WHITEBOARD_FONT_UNDERLINE;
const int Pb_MeetFontFlag_ARRAYSIZE = Pb_MeetFontFlag_MAX + 1;

enum Pb_Meet_FunctionCode {
  Pb_MEET_FUNCODE_AGENDA_BULLETIN = 0,
  Pb_MEET_FUNCODE_MATERIAL = 1,
  Pb_MEET_FUNCODE_SHAREDFILE = 2,
  Pb_MEET_FUNCODE_POSTIL = 3,
  Pb_MEET_FUNCODE_MESSAGE = 4,
  Pb_MEET_FUNCODE_VIDEOSTREAM = 5,
  Pb_MEET_FUNCODE_WHITEBOARD = 6,
  Pb_MEET_FUNCODE_WEBBROWSER = 7,
  Pb_MEET_FUNCODE_VOTERESULT = 8,
  Pb_MEET_FUNCODE_SIGNINRESULT = 9,
  Pb_MEET_FUNCODE_DOCUMENT = 10,
  Pb_Meet_FunctionCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_Meet_FunctionCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_Meet_FunctionCode_IsValid(int value);
const Pb_Meet_FunctionCode Pb_Meet_FunctionCode_MIN = Pb_MEET_FUNCODE_AGENDA_BULLETIN;
const Pb_Meet_FunctionCode Pb_Meet_FunctionCode_MAX = Pb_MEET_FUNCODE_DOCUMENT;
const int Pb_Meet_FunctionCode_ARRAYSIZE = Pb_Meet_FunctionCode_MAX + 1;

enum Pb_MeetPlayFlag {
  Pb_MEDIA_PLAYFLAG_ZERO = 0,
  Pb_MEDIA_PLAYFLAG_LOOP = 1,
  Pb_MeetPlayFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetPlayFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetPlayFlag_IsValid(int value);
const Pb_MeetPlayFlag Pb_MeetPlayFlag_MIN = Pb_MEDIA_PLAYFLAG_ZERO;
const Pb_MeetPlayFlag Pb_MeetPlayFlag_MAX = Pb_MEDIA_PLAYFLAG_LOOP;
const int Pb_MeetPlayFlag_ARRAYSIZE = Pb_MeetPlayFlag_MAX + 1;

enum Pb_MeetFaceID {
  Pb_MEET_FACEID_ZERO = 0,
  Pb_MEET_FACEID_MAINBG = 1,
  Pb_MEET_FACEID_SUBBG = 2,
  Pb_MEET_FACEID_LOGO = 3,
  Pb_MEET_FACEID_MEETNAME = 4,
  Pb_MEET_FACEID_MEMBERNAME = 5,
  Pb_MEET_FACEID_MEMBERCOMPANY = 6,
  Pb_MEET_FACEID_MEMBERJOB = 7,
  Pb_MEET_FACEID_SEATNAME = 8,
  Pb_MEET_FACEID_TIMER = 9,
  Pb_MEET_FACEID_COMPANY = 10,
  Pb_MEET_FACEID_SHOWFILE = 11,
  Pb_MEET_FACEID_COLTDTEXT = 12,
  Pb_MEET_FACE_LOGO_GEO = 13,
  Pb_MEET_FACE_topstatus_GEO = 14,
  Pb_MEET_FACE_checkin_GEO = 15,
  Pb_MEET_FACE_manage_GEO = 16,
  Pb_MEET_FACE_remark_GEO = 17,
  Pb_MEET_FACE_role_GEO = 18,
  Pb_MEET_FACE_ver_GEO = 19,
  Pb_MEET_FACE_SeatIcoShow_GEO = 20,
  Pb_MEET_FACEID_PROJECTIVE_MIANBG = 101,
  Pb_MEET_FACEID_PROJECTIVE_LOGO = 102,
  Pb_MEET_FACEID_PROJECTIVE_MEETNAME = 103,
  Pb_MEET_FACEID_PROJECTIVE_SEATNAME = 104,
  Pb_MEET_FACEID_PROJECTIVE_TIMER = 105,
  Pb_MEET_FACEID_PROJECTIVE_COMPANY = 106,
  Pb_MEET_FACEID_PROJECTIVE_SHOWFILE = 107,
  Pb_MEET_FACEID_PROJECTIVE_COLTDTEXT = 108,
  Pb_MeetFaceID_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFaceID_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFaceID_IsValid(int value);
const Pb_MeetFaceID Pb_MeetFaceID_MIN = Pb_MEET_FACEID_ZERO;
const Pb_MeetFaceID Pb_MeetFaceID_MAX = Pb_MEET_FACEID_PROJECTIVE_COLTDTEXT;
const int Pb_MeetFaceID_ARRAYSIZE = Pb_MeetFaceID_MAX + 1;

enum Pb_MeetFaceFontFlag {
  Pb_MEET_FONTFLAG_ZERO = 0,
  Pb_MEET_FONTFLAG_BOLD = 1,
  Pb_MEET_FONTFLAG_LEAN = 2,
  Pb_MEET_FONTFLAG_UNDERLINE = 4,
  Pb_MeetFaceFontFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFaceFontFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFaceFontFlag_IsValid(int value);
const Pb_MeetFaceFontFlag Pb_MeetFaceFontFlag_MIN = Pb_MEET_FONTFLAG_ZERO;
const Pb_MeetFaceFontFlag Pb_MeetFaceFontFlag_MAX = Pb_MEET_FONTFLAG_UNDERLINE;
const int Pb_MeetFaceFontFlag_ARRAYSIZE = Pb_MeetFaceFontFlag_MAX + 1;

enum Pb_MeetFaceFlag {
  Pb_MEET_FACEFLAG_ZERO = 0,
  Pb_MEET_FACEFLAG_SHOW = 1,
  Pb_MEET_FACEFLAG_TEXT = 2,
  Pb_MEET_FACEFLAG_ONLYTEXT = 4,
  Pb_MeetFaceFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetFaceFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetFaceFlag_IsValid(int value);
const Pb_MeetFaceFlag Pb_MeetFaceFlag_MIN = Pb_MEET_FACEFLAG_ZERO;
const Pb_MeetFaceFlag Pb_MeetFaceFlag_MAX = Pb_MEET_FACEFLAG_ONLYTEXT;
const int Pb_MeetFaceFlag_ARRAYSIZE = Pb_MeetFaceFlag_MAX + 1;

enum Pb_MeetStatisticFlag {
  Pb_MEET_QUERYSTATISTIC_ZERO = 0,
  Pb_MEET_QUERYSTATISTIC_BYMONTH = 1,
  Pb_MEET_QUERYSTATISTIC_BYQUARTER = 2,
  Pb_MEET_QUERYSTATISTIC_BYYEAR = 3,
  Pb_MeetStatisticFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_MeetStatisticFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_MeetStatisticFlag_IsValid(int value);
const Pb_MeetStatisticFlag Pb_MeetStatisticFlag_MIN = Pb_MEET_QUERYSTATISTIC_ZERO;
const Pb_MeetStatisticFlag Pb_MeetStatisticFlag_MAX = Pb_MEET_QUERYSTATISTIC_BYYEAR;
const int Pb_MeetStatisticFlag_ARRAYSIZE = Pb_MeetStatisticFlag_MAX + 1;

enum Pb_FileEvaluateFlag {
  Pb_FILEEVALUATE_FLAG_ZERO = 0,
  Pb_FILEEVALUATE_FLAG_SECRETARY = 1,
  Pb_FileEvaluateFlag_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Pb_FileEvaluateFlag_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Pb_FileEvaluateFlag_IsValid(int value);
const Pb_FileEvaluateFlag Pb_FileEvaluateFlag_MIN = Pb_FILEEVALUATE_FLAG_ZERO;
const Pb_FileEvaluateFlag Pb_FileEvaluateFlag_MAX = Pb_FILEEVALUATE_FLAG_SECRETARY;
const int Pb_FileEvaluateFlag_ARRAYSIZE = Pb_FileEvaluateFlag_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Pb_Error> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_DB_StatusCode> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_Type> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_Method> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_String_LenLimit> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_ProgramType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_CacheFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_FontAlignFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_DevicePlayStatus> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFaceStatus> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetDevicePropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_DeviceModifyFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_ContextPropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_AgendaType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_AgendaStatus> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_AdminLogonStatus> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_DeviceControlFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_LiftFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_Download_State> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_Download_Erro> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_Upload_State> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_Upload_Flag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MemberPropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MemberPermissionPropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetSignType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetRoomPropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_DeviceDirection> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_RoomDeviceFilterFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetStatus> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetPropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetMemberRole> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFileAttrib> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFilePropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFileQueryFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFileType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_TableCardType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_TableCardFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetSeatPropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetIMMSG_TYPE> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetIMMSG_QueryFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetVoteStatus> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetVoteType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetVoteMode> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetVote_SelType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetVotePropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetSignPropertyID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetPostilOperType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetPostilFigureType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFontFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_Meet_FunctionCode> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetPlayFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFaceID> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFaceFontFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetFaceFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_MeetStatisticFlag> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::Pb_FileEvaluateFlag> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Interface_5fMacro_2eproto__INCLUDED
