// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Interface_bullet.proto

package com.mogujie.tt.protobuf;

public final class InterfaceBullet {
  private InterfaceBullet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface pbui_Item_BulletDetailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_Item_BulletDetailInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>fixed32 bulletid = 1;</code>
     */
    int getBulletid();

    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>bytes title = 2;</code>
     */
    com.google.protobuf.ByteString getTitle();

    /**
     * <pre>
     *内容 
     * </pre>
     *
     * <code>bytes content = 3;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <pre>
     *类别
     * </pre>
     *
     * <code>fixed32 type = 4;</code>
     */
    int getType();

    /**
     * <pre>
     *开始时间
     * </pre>
     *
     * <code>fixed32 starttime = 5;</code>
     */
    int getStarttime();

    /**
     * <pre>
     *超时值
     * </pre>
     *
     * <code>fixed32 timeouts = 6;</code>
     */
    int getTimeouts();
  }
  /**
   * <pre>
   *会议公告
   * </pre>
   *
   * Protobuf type {@code pbui_Item_BulletDetailInfo}
   */
  public  static final class pbui_Item_BulletDetailInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_Item_BulletDetailInfo, pbui_Item_BulletDetailInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_Item_BulletDetailInfo)
      pbui_Item_BulletDetailInfoOrBuilder {
    private pbui_Item_BulletDetailInfo() {
      title_ = com.google.protobuf.ByteString.EMPTY;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int BULLETID_FIELD_NUMBER = 1;
    private int bulletid_;
    /**
     * <code>fixed32 bulletid = 1;</code>
     */
    public int getBulletid() {
      return bulletid_;
    }
    /**
     * <code>fixed32 bulletid = 1;</code>
     */
    private void setBulletid(int value) {
      
      bulletid_ = value;
    }
    /**
     * <code>fixed32 bulletid = 1;</code>
     */
    private void clearBulletid() {
      
      bulletid_ = 0;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString title_;
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>bytes title = 2;</code>
     */
    public com.google.protobuf.ByteString getTitle() {
      return title_;
    }
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>bytes title = 2;</code>
     */
    private void setTitle(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
    }
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>bytes title = 2;</code>
     */
    private void clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <pre>
     *内容 
     * </pre>
     *
     * <code>bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    /**
     * <pre>
     *内容 
     * </pre>
     *
     * <code>bytes content = 3;</code>
     */
    private void setContent(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      content_ = value;
    }
    /**
     * <pre>
     *内容 
     * </pre>
     *
     * <code>bytes content = 3;</code>
     */
    private void clearContent() {
      
      content_ = getDefaultInstance().getContent();
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     *类别
     * </pre>
     *
     * <code>fixed32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     *类别
     * </pre>
     *
     * <code>fixed32 type = 4;</code>
     */
    private void setType(int value) {
      
      type_ = value;
    }
    /**
     * <pre>
     *类别
     * </pre>
     *
     * <code>fixed32 type = 4;</code>
     */
    private void clearType() {
      
      type_ = 0;
    }

    public static final int STARTTIME_FIELD_NUMBER = 5;
    private int starttime_;
    /**
     * <pre>
     *开始时间
     * </pre>
     *
     * <code>fixed32 starttime = 5;</code>
     */
    public int getStarttime() {
      return starttime_;
    }
    /**
     * <pre>
     *开始时间
     * </pre>
     *
     * <code>fixed32 starttime = 5;</code>
     */
    private void setStarttime(int value) {
      
      starttime_ = value;
    }
    /**
     * <pre>
     *开始时间
     * </pre>
     *
     * <code>fixed32 starttime = 5;</code>
     */
    private void clearStarttime() {
      
      starttime_ = 0;
    }

    public static final int TIMEOUTS_FIELD_NUMBER = 6;
    private int timeouts_;
    /**
     * <pre>
     *超时值
     * </pre>
     *
     * <code>fixed32 timeouts = 6;</code>
     */
    public int getTimeouts() {
      return timeouts_;
    }
    /**
     * <pre>
     *超时值
     * </pre>
     *
     * <code>fixed32 timeouts = 6;</code>
     */
    private void setTimeouts(int value) {
      
      timeouts_ = value;
    }
    /**
     * <pre>
     *超时值
     * </pre>
     *
     * <code>fixed32 timeouts = 6;</code>
     */
    private void clearTimeouts() {
      
      timeouts_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bulletid_ != 0) {
        output.writeFixed32(1, bulletid_);
      }
      if (!title_.isEmpty()) {
        output.writeBytes(2, title_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(3, content_);
      }
      if (type_ != 0) {
        output.writeFixed32(4, type_);
      }
      if (starttime_ != 0) {
        output.writeFixed32(5, starttime_);
      }
      if (timeouts_ != 0) {
        output.writeFixed32(6, timeouts_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (bulletid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, bulletid_);
      }
      if (!title_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, title_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(4, type_);
      }
      if (starttime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(5, starttime_);
      }
      if (timeouts_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(6, timeouts_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *会议公告
     * </pre>
     *
     * Protobuf type {@code pbui_Item_BulletDetailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_Item_BulletDetailInfo)
        com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>fixed32 bulletid = 1;</code>
       */
      public int getBulletid() {
        return instance.getBulletid();
      }
      /**
       * <code>fixed32 bulletid = 1;</code>
       */
      public Builder setBulletid(int value) {
        copyOnWrite();
        instance.setBulletid(value);
        return this;
      }
      /**
       * <code>fixed32 bulletid = 1;</code>
       */
      public Builder clearBulletid() {
        copyOnWrite();
        instance.clearBulletid();
        return this;
      }

      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>bytes title = 2;</code>
       */
      public com.google.protobuf.ByteString getTitle() {
        return instance.getTitle();
      }
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>bytes title = 2;</code>
       */
      public Builder setTitle(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTitle(value);
        return this;
      }
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>bytes title = 2;</code>
       */
      public Builder clearTitle() {
        copyOnWrite();
        instance.clearTitle();
        return this;
      }

      /**
       * <pre>
       *内容 
       * </pre>
       *
       * <code>bytes content = 3;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return instance.getContent();
      }
      /**
       * <pre>
       *内容 
       * </pre>
       *
       * <code>bytes content = 3;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContent(value);
        return this;
      }
      /**
       * <pre>
       *内容 
       * </pre>
       *
       * <code>bytes content = 3;</code>
       */
      public Builder clearContent() {
        copyOnWrite();
        instance.clearContent();
        return this;
      }

      /**
       * <pre>
       *类别
       * </pre>
       *
       * <code>fixed32 type = 4;</code>
       */
      public int getType() {
        return instance.getType();
      }
      /**
       * <pre>
       *类别
       * </pre>
       *
       * <code>fixed32 type = 4;</code>
       */
      public Builder setType(int value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <pre>
       *类别
       * </pre>
       *
       * <code>fixed32 type = 4;</code>
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      /**
       * <pre>
       *开始时间
       * </pre>
       *
       * <code>fixed32 starttime = 5;</code>
       */
      public int getStarttime() {
        return instance.getStarttime();
      }
      /**
       * <pre>
       *开始时间
       * </pre>
       *
       * <code>fixed32 starttime = 5;</code>
       */
      public Builder setStarttime(int value) {
        copyOnWrite();
        instance.setStarttime(value);
        return this;
      }
      /**
       * <pre>
       *开始时间
       * </pre>
       *
       * <code>fixed32 starttime = 5;</code>
       */
      public Builder clearStarttime() {
        copyOnWrite();
        instance.clearStarttime();
        return this;
      }

      /**
       * <pre>
       *超时值
       * </pre>
       *
       * <code>fixed32 timeouts = 6;</code>
       */
      public int getTimeouts() {
        return instance.getTimeouts();
      }
      /**
       * <pre>
       *超时值
       * </pre>
       *
       * <code>fixed32 timeouts = 6;</code>
       */
      public Builder setTimeouts(int value) {
        copyOnWrite();
        instance.setTimeouts(value);
        return this;
      }
      /**
       * <pre>
       *超时值
       * </pre>
       *
       * <code>fixed32 timeouts = 6;</code>
       */
      public Builder clearTimeouts() {
        copyOnWrite();
        instance.clearTimeouts();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_Item_BulletDetailInfo)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo other = (com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo) arg1;
          bulletid_ = visitor.visitInt(bulletid_ != 0, bulletid_,
              other.bulletid_ != 0, other.bulletid_);
          title_ = visitor.visitByteString(title_ != com.google.protobuf.ByteString.EMPTY, title_,
              other.title_ != com.google.protobuf.ByteString.EMPTY, other.title_);
          content_ = visitor.visitByteString(content_ != com.google.protobuf.ByteString.EMPTY, content_,
              other.content_ != com.google.protobuf.ByteString.EMPTY, other.content_);
          type_ = visitor.visitInt(type_ != 0, type_,
              other.type_ != 0, other.type_);
          starttime_ = visitor.visitInt(starttime_ != 0, starttime_,
              other.starttime_ != 0, other.starttime_);
          timeouts_ = visitor.visitInt(timeouts_ != 0, timeouts_,
              other.timeouts_ != 0, other.timeouts_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 13: {

                  bulletid_ = input.readFixed32();
                  break;
                }
                case 18: {

                  title_ = input.readBytes();
                  break;
                }
                case 26: {

                  content_ = input.readBytes();
                  break;
                }
                case 37: {

                  type_ = input.readFixed32();
                  break;
                }
                case 45: {

                  starttime_ = input.readFixed32();
                  break;
                }
                case 53: {

                  timeouts_ = input.readFixed32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_Item_BulletDetailInfo)
    private static final com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_Item_BulletDetailInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_Item_BulletDetailInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_Item_BulletDetailInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_BulletDetailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_BulletDetailInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    java.util.List<com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo> 
        getItemList();
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo getItem(int index);
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    int getItemCount();
  }
  /**
   * <pre>
   *会议公告
   *Pb_TYPE_MEET_INTERFACE_MEETBULLET
   *call
   *method: add,del,modify,query,publish
   * </pre>
   *
   * Protobuf type {@code pbui_BulletDetailInfo}
   */
  public  static final class pbui_BulletDetailInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_BulletDetailInfo, pbui_BulletDetailInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_BulletDetailInfo)
      pbui_BulletDetailInfoOrBuilder {
    private pbui_BulletDetailInfo() {
      item_ = emptyProtobufList();
    }
    public static final int ITEM_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo> item_;
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    public java.util.List<com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo> getItemList() {
      return item_;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    public java.util.List<? extends com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfoOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    public int getItemCount() {
      return item_.size();
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo getItem(int index) {
      return item_.get(index);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    public com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfoOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    private void ensureItemIsMutable() {
      if (!item_.isModifiable()) {
        item_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
       }
    }

    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.set(index, value);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void setItem(
        int index, com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.set(index, builderForValue.build());
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void addItem(com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(value);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureItemIsMutable();
      item_.add(index, value);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void addItem(
        com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(builderForValue.build());
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void addItem(
        int index, com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.Builder builderForValue) {
      ensureItemIsMutable();
      item_.add(index, builderForValue.build());
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void addAllItem(
        java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo> values) {
      ensureItemIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, item_);
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void clearItem() {
      item_ = emptyProtobufList();
    }
    /**
     * <pre>
     * 
     * </pre>
     *
     * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
     */
    private void removeItem(int index) {
      ensureItemIsMutable();
      item_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(1, item_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, item_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *会议公告
     *Pb_TYPE_MEET_INTERFACE_MEETBULLET
     *call
     *method: add,del,modify,query,publish
     * </pre>
     *
     * Protobuf type {@code pbui_BulletDetailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_BulletDetailInfo)
        com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public java.util.List<com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo> getItemList() {
        return java.util.Collections.unmodifiableList(
            instance.getItemList());
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public int getItemCount() {
        return instance.getItemCount();
      }/**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo getItem(int index) {
        return instance.getItem(index);
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo value) {
        copyOnWrite();
        instance.setItem(index, value);
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder setItem(
          int index, com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setItem(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder addItem(com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo value) {
        copyOnWrite();
        instance.addItem(value);
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo value) {
        copyOnWrite();
        instance.addItem(index, value);
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder addItem(
          com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(builderForValue);
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder addItem(
          int index, com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addItem(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder addAllItem(
          java.lang.Iterable<? extends com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo> values) {
        copyOnWrite();
        instance.addAllItem(values);
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder clearItem() {
        copyOnWrite();
        instance.clearItem();
        return this;
      }
      /**
       * <pre>
       * 
       * </pre>
       *
       * <code>repeated .pbui_Item_BulletDetailInfo item = 1;</code>
       */
      public Builder removeItem(int index) {
        copyOnWrite();
        instance.removeItem(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_BulletDetailInfo)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          item_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo other = (com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo) arg1;
          item_= visitor.visitList(item_, other.item_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!item_.isModifiable()) {
                    item_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(item_);
                  }
                  item_.add(
                      input.readMessage(com.mogujie.tt.protobuf.InterfaceBullet.pbui_Item_BulletDetailInfo.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_BulletDetailInfo)
    private static final com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_BulletDetailInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BulletDetailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_BulletDetailInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_BulletDetailInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface pbui_BigBulletDetailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pbui_BigBulletDetailInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>bytes text = 1;</code>
     */
    com.google.protobuf.ByteString getText();
  }
  /**
   * <pre>
   *会议长文本公告
   *Pb_TYPE_MEET_INTERFACE_MEETBULLET
   *call,callback
   *method: request(获取),update(修改)
   * </pre>
   *
   * Protobuf type {@code pbui_BigBulletDetailInfo}
   */
  public  static final class pbui_BigBulletDetailInfo extends
      com.google.protobuf.GeneratedMessageLite<
          pbui_BigBulletDetailInfo, pbui_BigBulletDetailInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:pbui_BigBulletDetailInfo)
      pbui_BigBulletDetailInfoOrBuilder {
    private pbui_BigBulletDetailInfo() {
      text_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int TEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString text_;
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>bytes text = 1;</code>
     */
    public com.google.protobuf.ByteString getText() {
      return text_;
    }
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>bytes text = 1;</code>
     */
    private void setText(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      text_ = value;
    }
    /**
     * <pre>
     *标题
     * </pre>
     *
     * <code>bytes text = 1;</code>
     */
    private void clearText() {
      
      text_ = getDefaultInstance().getText();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!text_.isEmpty()) {
        output.writeBytes(1, text_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!text_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, text_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     *会议长文本公告
     *Pb_TYPE_MEET_INTERFACE_MEETBULLET
     *call,callback
     *method: request(获取),update(修改)
     * </pre>
     *
     * Protobuf type {@code pbui_BigBulletDetailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:pbui_BigBulletDetailInfo)
        com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfoOrBuilder {
      // Construct using com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>bytes text = 1;</code>
       */
      public com.google.protobuf.ByteString getText() {
        return instance.getText();
      }
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>bytes text = 1;</code>
       */
      public Builder setText(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setText(value);
        return this;
      }
      /**
       * <pre>
       *标题
       * </pre>
       *
       * <code>bytes text = 1;</code>
       */
      public Builder clearText() {
        copyOnWrite();
        instance.clearText();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pbui_BigBulletDetailInfo)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo other = (com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo) arg1;
          text_ = visitor.visitByteString(text_ != com.google.protobuf.ByteString.EMPTY, text_,
              other.text_ != com.google.protobuf.ByteString.EMPTY, other.text_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {

                  text_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:pbui_BigBulletDetailInfo)
    private static final com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pbui_BigBulletDetailInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mogujie.tt.protobuf.InterfaceBullet.pbui_BigBulletDetailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<pbui_BigBulletDetailInfo> PARSER;

    public static com.google.protobuf.Parser<pbui_BigBulletDetailInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
